### ISSUE TITLE
v3 not working

### ISSUE THREAD

**Issue by elBelgg** [degabut/examples#1]
I cannot make the v3 of the Bot work. I have everything configurated properly, but I am getting this error.

**LOGS:**
[Nest] 18  - 08/27/2023, 11:51:30 PM   ERROR [ExceptionHandler] Invalid URL
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at parseURL (/usr/src/app/node_modules/.pnpm/undici@5.8.0/node_modules/undici/lib/core/util.js:76:11)
    at Object.parseOrigin (/usr/src/app/node_modules/.pnpm/undici@5.8.0/node_modules/undici/lib/core/util.js:125:9)
    at new Pool (/usr/src/app/node_modules/.pnpm/undici@5.8.0/node_modules/undici/lib/pool.js:62:23)
    at new REST (/usr/src/app/node_modules/.pnpm/lavaclient@4.1.1/node_modules/lavaclient/dist/lib/node/REST.js:8:21)
    at new Node (/usr/src/app/node_modules/.pnpm/lavaclient@4.1.1/node_modules/lavaclient/dist/lib/node/Node.js:19:21)
    at new QueuePlayerGateway (/usr/src/app/dist/queue-player/queue-player.gateway.js:71:22)
    at Injector.instantiateClass (/usr/src/app/node_modules/.pnpm/@nestjs+core@9.4.2_@nestjs+common@9.4.2_@nestjs+websockets@9.4.2_reflect-metadata@0.1.13_rxjs@7.5.6/node_modules/@nestjs/core/injector/injector.js:351:19)

**Comment by SuspiciousLookingOwl** [comment]
Sorry for the late response, didn't have this repo watched.

When did the error appears? Was it when you are trying to run the container?

I just tried to run the container following the [v3 instruction](https://github.com/degabut/examples/tree/main/v3) and played a song without any issue.

**Comment by elBelgg** [comment]
The error appeared after starting it. I had done it in Docker, that may have been the problem

**Comment by SuspiciousLookingOwl** [comment]
I'm guessing the error caused by passing an incorrect `LAVA_HOST` environment variable value.

On the [example](https://github.com/degabut/examples/blob/main/v3/.env.example#L4C5-L4C5), the default value for `LAVA_HOST` is `degabut-lavalink`, which is the Lavalink's container name inside the [docker-compose.yml](https://github.com/degabut/examples/blob/main/v3/docker-compose.yml#L24-L25) file, if you use docker compose, it will resolve `degabut-lavalink` with the service's hostname

From [Docker Compose Networking](https://docs.docker.com/compose/networking/):
> By default Compose sets up a single [network](https://docs.docker.com/engine/reference/commandline/network_create/) for your app. Each container for a service joins the default network and is both reachable by other containers on that network, and discoverable by them at a hostname identical to the container name.

If you run lavalink on your own (running it locally), you need to change the `LAVA_HOST` accordingly (e.g. `localhost`)
